'use strict';

module.exports =
    angular.module('<%= appname %>', [
        //load external modules here, e.g.:
        //'ui.router',
        //'ui.bootstrap',
        //require('../../../tmp/templates').name, //html templates in $templateCache generated by Gulp
        require('../common').name //useful directives, filters, services shared across the app
        //load your app modules here, e.g.:
        //require('./frontend').name
        //require('./admin').name
    ]);
